### ISSUE TITLE
GetUser 0auth bearer /login gives an error

### ISSUE THREAD

**Issue by mr-od** [sb-elliot-7s/ecommerce-app-fastapi#1]
I've been trying to get the 0Auth get user /login to work all to no avail. I changed the url to match the main route login url but it won't work. With not found or 422 error gets returned. This only happens with the fastAPI swaggerUI. But everything works well on insomnia and postman. That's the plan I guess?

**Comment by sb-elliot-7s** [comment]
You are trying to login via browser http://localhost:8000/docs#/ or postman? In postman everything works for me. To work in the documentation (http://localhost:8000/docs#/) the login must be by username field

**Comment by mr-od** [comment]
Yeah I found out that everything works fine with postman. With swagger it doesn't. With the /login url, it doesn't work on swagger even if you change the 0Auth to use username. I think it's because of the way the 0Auth is configured. But it's ok. Swagger redocs + postman is awesome. Thanks for the reply. I appreciate. I think we can close the issue.
